import Database from "better-sqlite3";
import { describe, expect, it } from "vitest";
import { applyMigrations } from "./db/applyMigrations.js";
import { authenticate, changePassword, createInvitation, createSession, getSessionUser, hashPassword, listUsers, registerWithInvitation, revokeInvitation, revokeUserSessions, setUserDisabled, verifyPassword } from "./auth.js";

describe("invitation authentication", () => {
  const setup = () => { const db = new Database(":memory:"); applyMigrations(db); db.prepare("INSERT INTO users (id,username,password_hash,role,created_at_utc) VALUES ('admin-id','admin',?,'ADMIN',?)").run(hashPassword("admin-test-password"), new Date().toISOString()); return db; };
  it("hashes passwords and authenticates without storing plaintext", () => { expect(verifyPassword("admin-test-password", hashPassword("admin-test-password"))).toBe(true); expect(authenticate(setup(), "admin", "admin-test-password")?.role).toBe("ADMIN"); });
  it("requires an active invitation and consumes its configured use", () => { const db = setup(); const invite = createInvitation(db, "admin-id", { maxUses: 1 }); const user = registerWithInvitation(db, { username: "angler.one", password: "securepass10", invitationCode: invite.code }); expect(user.role).toBe("USER"); expect(() => registerWithInvitation(db, { username: "angler.two", password: "securepass10", invitationCode: invite.code })).toThrow("INVITATION_INVALID_OR_EXPIRED"); });
  it("revokes invitations and stores only session token hashes", () => { const db = setup(); const invite = createInvitation(db, "admin-id", {}); expect(revokeInvitation(db, invite.id)).toBe(true); expect(() => registerWithInvitation(db, { username: "angler.one", password: "securepass10", invitationCode: invite.code })).toThrow("INVITATION_INVALID_OR_EXPIRED"); const session = createSession(db, "admin-id"); expect(getSessionUser(db, session.token)).toEqual(expect.objectContaining({ username: "admin" })); expect((db.prepare("SELECT token_hash FROM user_sessions").get() as { token_hash: string }).token_hash).not.toBe(session.token); });
  it("changes a password and revokes every old session", () => { const db = setup(); const oldSession = createSession(db, "admin-id"); changePassword(db, "admin-id", "admin-test-password", "a-new-secure-password"); expect(getSessionUser(db, oldSession.token)).toBeNull(); expect(() => changePassword(db, "admin-id", "admin-test-password", "another-secure-password")).toThrow("CURRENT_PASSWORD_INVALID"); });
  it("lets an administrator disable a user and revoke sessions", () => { const db = setup(); const invite = createInvitation(db, "admin-id", {}); const user = registerWithInvitation(db, { username: "angler.user", password: "securepass10", invitationCode: invite.code }); createSession(db, user.id); expect(listUsers(db).find((item) => item.id === user.id)?.activeSessions).toBe(1); expect(revokeUserSessions(db, user.id)).toBe(1); setUserDisabled(db, "admin-id", user.id, true); expect(listUsers(db).find((item) => item.id === user.id)?.disabledAtUtc).toBeTruthy(); expect(() => setUserDisabled(db, "admin-id", "admin-id", true)).toThrow("ADMIN_CANNOT_DISABLE_SELF"); });
});
