import { useEffect,useMemo,useRef,useState } from 'react';
import { MapContainer,Marker,Popup,TileLayer,useMap,useMapEvents } from 'react-leaflet';
import L from 'leaflet';
import type { LocationPoint } from '../types';
import 'leaflet/dist/leaflet.css';

const markerIcon=L.divIcon({className:'tideline-marker',html:'<span aria-hidden="true">●</span>',iconSize:[34,44],iconAnchor:[17,42]});
function MapController({point,onCoordinate}:{point:LocationPoint|null;onCoordinate:(lat:number,lon:number)=>void}){const map=useMap();useEffect(()=>{if(point)map.flyTo([point.latitude,point.longitude],14,{duration:.7})},[map,point]);useMapEvents({click(event){onCoordinate(event.latlng.lat,event.latlng.lng)}});return null}
export function MapView({point,onCoordinate}:{point:LocationPoint|null;onCoordinate:(lat:number,lon:number)=>void}){const marker=useRef<L.Marker|null>(null),[tileError,setTileError]=useState(false);const center=useMemo<L.LatLngExpression>(()=>point?[point.latitude,point.longitude]:[-25.5,134.5],[point]);return <section className="real-map" aria-label="交互式钓点地图">{tileError?<div className="map-error" role="alert">地图瓦片加载失败。仍可通过搜索或手动坐标选择位置。</div>:null}<MapContainer center={center} zoom={point?14:4} scrollWheelZoom className="leaflet-map"><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>' url="https://tile.openstreetmap.org/{z}/{x}/{y}.png" eventHandlers={{tileerror:()=>setTileError(true),tileload:()=>setTileError(false)}}/><MapController point={point} onCoordinate={onCoordinate}/>{point?<Marker ref={marker} position={[point.latitude,point.longitude]} icon={markerIcon} draggable eventHandlers={{dragend(){const latlng=marker.current?.getLatLng();if(latlng)onCoordinate(latlng.lat,latlng.lng)}}}><Popup><b>{point.name}</b><br/>{point.address}<br/>{point.latitude.toFixed(5)}, {point.longitude.toFixed(5)}</Popup></Marker>:null}</MapContainer><div className="map-help">点击地图或拖动标记可调整下竿位置</div></section>}
