import type { GeocodingProvider } from './ports.js';
import { markHealth } from '../services/health.js';

export type GeocodingResult={id:string;name:string;address:string;latitude:number;longitude:number;state:string;timezone:string;countryCode:'AU'};
type PhotonFeature={geometry:{coordinates:[number,number]};properties:Record<string,string|number|undefined>};
type PhotonResponse={features:PhotonFeature[]};
const stateCodes:Record<string,string>={'New South Wales':'NSW','Victoria':'VIC','Queensland':'QLD','Western Australia':'WA','South Australia':'SA','Tasmania':'TAS','Northern Territory':'NT','Australian Capital Territory':'ACT'};
const timezones:Record<string,string>={NSW:'Australia/Sydney',VIC:'Australia/Melbourne',QLD:'Australia/Brisbane',WA:'Australia/Perth',SA:'Australia/Adelaide',TAS:'Australia/Hobart',NT:'Australia/Darwin',ACT:'Australia/Sydney'};
const cache=new Map<string,{expires:number,data:GeocodingResult[]}>();
export const normalizePhotonFeature=(f:PhotonFeature):GeocodingResult=>{const p=f.properties;const state=stateCodes[String(p.state??'')]??'NSW';const parts=[p.name,p.street,p.district,p.city,p.county,p.state,p.postcode,'Australia'].filter(Boolean).map(String);return {id:`${p.osm_type??'x'}-${p.osm_id??f.geometry.coordinates.join('-')}`,name:String(p.name??p.city??p.locality??'Selected location'),address:[...new Set(parts)].join(', '),longitude:f.geometry.coordinates[0],latitude:f.geometry.coordinates[1],state,timezone:timezones[state]??'Australia/Sydney',countryCode:'AU'}};
async function photon(path:string,params:URLSearchParams){const url=new URL(path,process.env.PHOTON_BASE_URL??'https://photon.komoot.io');url.search=params.toString();const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),7000);try{const response=await fetch(url,{signal:controller.signal,headers:{'user-agent':process.env.GEOCODING_USER_AGENT??'TideLine/0.1'}});if(!response.ok)throw new Error(`Photon HTTP ${response.status}`);const data=await response.json() as PhotonResponse;markHealth('geocoding',true);return data.features.filter(f=>String(f.properties.countrycode??'').toUpperCase()==='AU').map(normalizePhotonFeature)}catch(error){markHealth('geocoding',false,error);throw new Error('地址搜索服务暂时不可用',{cause:error})}finally{clearTimeout(timer)}}
export class PhotonGeocoding implements GeocodingProvider{
  async search(query:string,focus?:{latitude:number;longitude:number}){const key=`q:${query.toLowerCase()}:${focus?.latitude.toFixed(2)??''}:${focus?.longitude.toFixed(2)??''}`;const hit=cache.get(key);if(hit&&hit.expires>Date.now())return hit.data;const params=new URLSearchParams({q:query,limit:'8',countrycode:'AU',lang:'en',bbox:'112,-44,154,-10'});if(focus){params.set('lat',String(focus.latitude));params.set('lon',String(focus.longitude));params.set('zoom','8')}const data=await photon('/api/',params);cache.set(key,{expires:Date.now()+10*60_000,data});return data}
  async reverse(latitude:number,longitude:number){const key=`r:${latitude.toFixed(4)}:${longitude.toFixed(4)}`;const hit=cache.get(key);if(hit&&hit.expires>Date.now())return hit.data[0]??null;const data=await photon('/reverse',new URLSearchParams({lat:String(latitude),lon:String(longitude),limit:'1',lang:'en'}));cache.set(key,{expires:Date.now()+24*3600_000,data});return data[0]??null}
}
