export type RegulationEntry = { state: string; authority: string; rulesUrl: string; licenceUrl: string | null; marineParksUrl: string | null; lastVerifiedAt: string; status: "REAL" | "NOT_APPLICABLE"; notice: string };
const verified = "2026-07-19";
const entries: Record<string, Omit<RegulationEntry, "state">> = {
  NSW: { authority: "NSW Government / DPIRD Fisheries", rulesUrl: "https://www.nsw.gov.au/sport-and-recreation/recreational-fishing", licenceUrl: "https://www.service.nsw.gov.au/services/recreational-fishing-licence", marineParksUrl: "https://www.environment.nsw.gov.au/topics/parks-reserves-and-protected-areas/types-of-protected-areas/marine-protected-areas", lastVerifiedAt: verified, status: "REAL", notice: "请在出发前核对尺寸、袋限、禁渔期、渔具限制、海洋公园和临时关闭。" },
  QLD: { authority: "Queensland Government", rulesUrl: "https://www.qld.gov.au/recreation/activities/boating-fishing/rec-fishing/rules", licenceUrl: null, marineParksUrl: "https://parks.desi.qld.gov.au/parks/great-sandy-marine/zoning", lastVerifiedAt: verified, status: "REAL", notice: "部分水域需要SIPS许可；请核对当地分区、闭区和物种规则。" },
  VIC: { authority: "Victorian Fisheries Authority", rulesUrl: "https://vfa.vic.gov.au/recreational-fishing/recreational-fishing-guide", licenceUrl: "https://www.service.vic.gov.au/find-services/outdoor-and-recreation/buy-a-victorian-recreational-fishing-licence", marineParksUrl: "https://www.parks.vic.gov.au/get-into-nature/safety-in-nature/marine-and-coastal-safety", lastVerifiedAt: verified, status: "REAL", notice: "请核对许可证、尺寸和数量限制、禁渔期及禁钓保护区。" },
  WA: { authority: "Government of Western Australia DPIRD", rulesUrl: "https://www.wa.gov.au/organisation/department-of-primary-industries-and-regional-development/recreational-fishing", licenceUrl: "https://www.wa.gov.au/service/natural-resources/fisheries/apply-or-renew-recreational-fishing-licence", marineParksUrl: "https://www.dbca.wa.gov.au/management/marine", lastVerifiedAt: verified, status: "REAL", notice: "WA不同生物区、季节和捕捞方式规则不同，请打开官方入口核实。" },
  SA: { authority: "PIRSA", rulesUrl: "https://pir.sa.gov.au/recreational_fishing", licenceUrl: null, marineParksUrl: "https://www.environment.sa.gov.au/topics/marine-parks", lastVerifiedAt: verified, status: "REAL", notice: "请核对物种限制、闭区、装备限制和海洋公园分区。" },
  TAS: { authority: "Tasmanian Government", rulesUrl: "https://fishing.tas.gov.au/", licenceUrl: "https://fishing.tas.gov.au/licence", marineParksUrl: "https://nre.tas.gov.au/conservation/conservation-on-sea/marine-reserves", lastVerifiedAt: verified, status: "REAL", notice: "海钓和内陆渔业许可体系不同，请根据目标水域进入对应官方规则。" },
  NT: { authority: "Northern Territory Government", rulesUrl: "https://nt.gov.au/marine/recreational-fishing", licenceUrl: null, marineParksUrl: "https://nt.gov.au/parks/find-a-park", lastVerifiedAt: verified, status: "REAL", notice: "请核对区域关闭、保护物种、尺寸袋限以及原住民水域许可要求。" },
  ACT: { authority: "ACT Government", rulesUrl: "https://www.cityservices.act.gov.au/public-land/public-spaces-and-facilities/recreational-fishing", licenceUrl: null, marineParksUrl: null, lastVerifiedAt: verified, status: "REAL", notice: "ACT为内陆水域，请核对允许水域、禁用装备和物种规定。" },
};
export function getRegulationEntry(state: string): RegulationEntry { const key = String(state ?? "").trim().toUpperCase(), entry = entries[key]; return entry ? { state: key, ...entry } : { state: key || "UNKNOWN", authority: "Unknown", rulesUrl: "", licenceUrl: null, marineParksUrl: null, lastVerifiedAt: verified, status: "NOT_APPLICABLE", notice: "无法识别州或领地，请手动打开所在地政府渔业主管部门。" }; }
