import type { FishingLog,Forecast,LocationPoint,SavedSpot,TideSource } from './types';
async function json<T>(response:Response,message:string){if(!response.ok){const body=await response.json().catch(()=>null) as {reason?:string}|null;throw new Error(body?.reason??message)}return response.json() as Promise<T>}
export async function searchLocations(query:string,focus?:{latitude:number;longitude:number},signal?:AbortSignal){const params=new URLSearchParams({q:query});if(focus){params.set('lat',String(focus.latitude));params.set('lon',String(focus.longitude))}const result=await json<{data:LocationPoint[]}>(await fetch(`/api/geocode/search?${params}`,{signal}),'地址搜索服务暂时不可用');return result.data}
export async function reverseLocation(latitude:number,longitude:number,signal?:AbortSignal){const result=await json<{data:LocationPoint|null}>(await fetch(`/api/geocode/reverse?lat=${latitude}&lon=${longitude}`,{signal}),'反向地址解析失败');return result.data}
export async function getForecast(point:LocationPoint,spotType:string,fishingMethod:string,preferredTideSource:TideSource='BOM_OFFICIAL'){const params=new URLSearchParams({spotId:point.id,lat:String(point.latitude),lon:String(point.longitude),name:point.name,address:point.address,state:point.state,timezone:point.timezone,spotType,waterType:spotType==='freshwater'?'freshwater':spotType==='estuary'?'estuary':'coastal',fishingMethod,preferredTideSource});return json<Forecast>(await fetch(`/api/forecast?${params}`),'预测服务暂时不可用')}
export async function getSpots(){return json<SavedSpot[]>(await fetch('/api/spots'),'收藏钓点读取失败')}
export async function saveSpot(point:LocationPoint,spotType:string,fishingMethod:string){return json<SavedSpot>(await fetch('/api/spots',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...point,spotType,fishingMethod,waterType:spotType==='freshwater'?'freshwater':'estuary_or_harbour'})}),'钓点保存失败')}
export async function saveEnvironmentPreferences(spotId:string,preferredTideSource:TideSource,options:Record<string,unknown>={}){return json<{status:string}>(await fetch(`/api/spots/${encodeURIComponent(spotId)}/environment-preferences`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({preferredTideSource,...options})}),'潮汐评分来源保存失败')}
export async function getLogs(){return json<FishingLog[]>(await fetch('/api/logs'),'实钓历史读取失败')}
export async function saveLog(input:Record<string,unknown>){return json<{id:string}>(await fetch('/api/logs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}),'实钓记录保存失败，请先保存钓点')}
export async function getAnalytics(){return json<{sessions:number;catches:number;bites:number;rating:number;blankRate:number;insufficientSample:boolean}>(await fetch('/api/analytics'),'分析读取失败')}
export async function getSystemStatus(){return json<Record<string,unknown>>(await fetch('/api/system-status'),'系统状态读取失败')}
